language: rust

cache: cargo

rust:
  - stable
  - nightly

os:
  - linux
  - osx

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly

script:
  - cargo build --verbose --all
  - cargo test --verbose --all

branches:
  only:
    - rust
